services:
  postgres:
    platform: linux/x86_64
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./app/db/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-drf-nginx-jupyter-network
  drf:
    platform: linux/x86_64
    image: tyamadabiodataeng/django-drf-dev
    container_name: drf
    build:
      context: ./app
      args:
        DIR_WORK: "/usr/src/app"
        ENV_YML: "environment.yaml"
        VENV: "bioinfo"
        DIR_CONDA: "/opt/conda"
        REQ_DIR: "requirements/"
        REQ_TXT: "dev.txt"
    command: gunicorn config.wsgi.dev:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    expose:
      - "8000"
    env_file:
      - ./app/db/.env.dev
    depends_on:
      - postgres
    networks:
      - postgres-drf-nginx-jupyter-network
  nginx:
    platform: linux/x86_64
    image: tyamadabiodataeng/django-drf-nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - drf
    networks:
      - postgres-drf-nginx-jupyter-network
  jupyter:
    platform: linux/x86_64
    build: 
      context: ./notebooks
      dockerfile: Dockerfile
      args:
        DIR_WORK: "/usr/src/app/notebooks"
        ENV_YML: "environment.yaml"
        VENV: "bioinfo"
        DIR_CONDA: "/opt/conda"
        REQ_TXT: "requirements.txt"
    image: tyamadabiodataeng/django-drf-jupyter
    container_name: jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - .:/usr/src/app
    tty: true
    stdin_open: true
    depends_on:
      - nginx
    networks:
      - postgres-drf-nginx-jupyter-network

networks:
  postgres-drf-nginx-jupyter-network:
    driver: bridge

volumes:
  postgres_data:
